### ISSUE TITLE
More information about the environment in which the code runs

### ISSUE THREAD

**Issue by yiqian-zyq** [AcherStyx/CoCap#8]
I found that using some specific versions of CUDA and PyTorch may cause segfaults, dynamic link library exceptions, etc., making the code unable to be reproduced. I hope the author can provide information on a runnable environment (the version of the required library)
thank you

**Comment by Yaojie-Shen** [comment]
> I found that using some specific versions of CUDA and PyTorch may cause segfaults, dynamic link library exceptions, etc., making the code unable to be reproduced. I hope the author can provide information on a runnable environment (the version of the required library) thank you

Hi @yiqian-zyq , thank you for your feedback!

Our experiment environment is constantly evolving, and as such, the code does not have stringent requirements on specific PyTorch versions. 🤔
Our recent experiments were conducted on PyTorch 2 (specifically versions 2.1.0 and 2.0.1), and everything appears to be functioning correctly. I hope this information proves helpful for debugging purposes.

Feel free to share a more detailed error message if possible.
Thanks!

**Comment by yiqian-zyq** [comment]
In fact, my environment is based on python3.11+PyTorch2.1.2+CUDA11.8. It seems that there should be no problems. I can share the error message.

WARNING [01/26 20:36:53][Rank 3][meter.py:  66]: Meter is not specified!
INFO    [01/26 20:36:53][Rank 0][build.py:  77]: Model total parameters: 171,010,240
WARNING [01/26 20:36:53][Rank 0][meter.py:  66]: Meter is not specified!
WARNING [01/26 20:36:53][Rank 1][meter.py:  66]: Meter is not specified!
WARNING [01/26 20:36:53][Rank 2][meter.py:  66]: Meter is not specified!
Train: 1/20:   0%|                                                                                                                        | 0/6097 [00:00<?, ?it/s]ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
Train: 1/20:   0%|                                                                                                                        | 0/6097 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/code/CoCap/mm_video/run_net.py", line 41, in <module>
    main()
  File "/data/code/CoCap/mm_video/run_net.py", line 23, in main
    mp.spawn(run_trainer, args=(cfg,), nprocs=cfg.SYS.NUM_GPU)
  File "/home/hdu/miniconda3/envs/cocap/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdu/miniconda3/envs/cocap/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
    while not context.join():
              ^^^^^^^^^^^^^^
  File "/home/hdu/miniconda3/envs/cocap/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/hdu/miniconda3/envs/cocap/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdu/miniconda3/envs/cocap/lib/python3.11/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/home/hdu/miniconda3/envs/cocap/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdu/miniconda3/envs/cocap/lib/python3.11/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 12822) is killed by signal: Segmentation fault.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hdu/miniconda3/envs/cocap/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/data/code/CoCap/mm_video/run_net.py", line 37, in run_trainer
    trainer.train()
  File "/data/code/CoCap/mm_video/trainer/build.py", line 272, in train
    self._on_train()
  File "/data/code/CoCap/mm_video/trainer/build.py", line 113, in _on_train
    self._on_train_epoch()
  File "/data/code/CoCap/mm_video/trainer/build.py", line 158, in _on_train_epoch
    for cur_step, inputs in enumerate(dataloader):
  File "/home/hdu/miniconda3/envs/cocap/lib/python3.11/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/data/code/CoCap/mm_video/utils/train_utils.py", line 62, in __iter__
    self.preload()
  File "/data/code/CoCap/mm_video/utils/train_utils.py", line 35, in preload
    self.batch = next(self.loader)
                 ^^^^^^^^^^^^^^^^^
  File "/home/hdu/miniconda3/envs/cocap/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/hdu/miniconda3/envs/cocap/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
                ^^^^^^^^^^^^^^^^
  File "/home/hdu/miniconda3/envs/cocap/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1284, in _get_data
    success, data = self._try_get_data()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/home/hdu/miniconda3/envs/cocap/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1145, in _try_get_data
    raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
RuntimeError: DataLoader worker (pid(s) 12822) exited unexpectedly

Also, I checked the debug log and it stopped here：
   compressed_video_transformer.residual_encoder.transformer.resblocks.1.attn.out_proj.bias
   compressed_video_transformer.residual_encoder.transformer.resblocks.1.ln_1.bias
   compressed_video_transformer.residual_encoder.transformer.resblocks.1.ln_1.weight
   compressed_video_transformer.residual_encoder.transformer.resblocks.1.ln_2.bias
   compressed_video_transformer.residual_encoder.transformer.resblocks.1.ln_2.weight
   compressed_video_transformer.residual_encoder.transformer.resblocks.1.mlp.c_fc.bias
   compressed_video_transformer.residual_encoder.transformer.resblocks.1.mlp.c_proj.bias
[01/26 20:36:53][DEBUG][Rank 2] optimizer.py:  26: Parameter for optimizer BertAdam is {'lr': 0.0001, 'warmup': 0.1, 'schedule': 'warmup_constant', 'weight_decay': 0.01, 'max_grad_norm': 1.0, 't_total': 30500.0}
[01/26 20:36:53][DEBUG][Rank 2] build.py: 100: Auto resume is disabled.
[01/26 20:36:53][WARNING][Rank 2] meter.py:  66: Meter is not specified!
[01/26 20:36:53][DEBUG][Rank 2] build.py: 109: Epoch 1/20
[01/26 20:36:53][DEBUG][Rank 0] build.py: 134: set train sampler step to 0
[01/26 20:36:53][DEBUG][Rank 3] build.py: 134: set train sampler step to 0
[01/26 20:36:53][DEBUG][Rank 1] build.py: 134: set train sampler step to 0
[01/26 20:36:53][DEBUG][Rank 2] build.py: 134: set train sampler step to 0
[01/26 20:36:53][DEBUG][Rank 0] build.py: 142: Building CudaPreFetcher...
[01/26 20:36:53][DEBUG][Rank 3] build.py: 142: Building CudaPreFetcher...
[01/26 20:36:53][DEBUG][Rank 2] build.py: 142: Building CudaPreFetcher...
[01/26 20:36:53][DEBUG][Rank 1] build.py: 142: Building CudaPreFetcher...
[01/26 20:36:53][DEBUG][Rank 3] build.py: 157: Running train epoch for-loop...
[01/26 20:36:53][DEBUG][Rank 0] build.py: 157: Running train epoch for-loop...
[01/26 20:36:53][DEBUG][Rank 2] build.py: 157: Running train epoch for-loop...
[01/26 20:36:53][DEBUG][Rank 1] build.py: 157: Running train epoch for-loop...

It looks like there might be some problem with VIdeo Reader, but I'm not sure
Hope you can provide some guidance, I've been stuck here for a day!!!

**Comment by Yaojie-Shen** [comment]
Thank you for your information!

Can you pass the test case for `cv_reader` both on my video in the repo and your own videos?

```bash
cv_reader ./test_data/h264_sample.mp4 ./test_output
```

Also, validate whether your videos are accurately converted to the H.264 format and ensure that the video files are not corrupted. Please note that our reader only supports H.264/H.265 formats.

As a suggestion, it might be beneficial to initially run `cv_reader` across all your videos to check for any potential errors during the reading process.

**Comment by yiqian-zyq** [comment]
This problem should have nothing to do with data. I updated the Nvidia driver and CUDA to the latest versions and the problem was solved.
